/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.InlineResponse2001GeoLocation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A geographical information set describing the location of this property.&lt;br&gt;&lt;br&gt;See also &lt;a href&#x3D;\&quot;#locationtypes\&quot;&gt;in the appendix&lt;/a&gt;.
 */
@ApiModel(description = "A geographical information set describing the location of this property.<br><br>See also <a href=\"#locationtypes\">in the appendix</a>.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-07T12:22:24.387616647Z[Etc/UTC]")
public class InlineResponse2001Geo {
  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private String language;

  public static final String SERIALIZED_NAME_FORMATTED_ADDRESS = "formatted_address";
  @SerializedName(SERIALIZED_NAME_FORMATTED_ADDRESS)
  private String formattedAddress;

  public static final String SERIALIZED_NAME_ROUTE = "route";
  @SerializedName(SERIALIZED_NAME_ROUTE)
  private String route;

  public static final String SERIALIZED_NAME_STREET_NUMBER = "street_number";
  @SerializedName(SERIALIZED_NAME_STREET_NUMBER)
  private String streetNumber;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postal_code";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_LOCALITY = "locality";
  @SerializedName(SERIALIZED_NAME_LOCALITY)
  private String locality;

  public static final String SERIALIZED_NAME_SUBLOCALITY = "sublocality";
  @SerializedName(SERIALIZED_NAME_SUBLOCALITY)
  private String sublocality;

  public static final String SERIALIZED_NAME_SUBLOCALITY_LEVEL1 = "sublocality_level_1";
  @SerializedName(SERIALIZED_NAME_SUBLOCALITY_LEVEL1)
  private String sublocalityLevel1;

  public static final String SERIALIZED_NAME_SUBLOCALITY_LEVEL2 = "sublocality_level_2";
  @SerializedName(SERIALIZED_NAME_SUBLOCALITY_LEVEL2)
  private String sublocalityLevel2;

  public static final String SERIALIZED_NAME_SUBLOCALITY_LEVEL3 = "sublocality_level_3";
  @SerializedName(SERIALIZED_NAME_SUBLOCALITY_LEVEL3)
  private String sublocalityLevel3;

  public static final String SERIALIZED_NAME_SUBLOCALITY_LEVEL4 = "sublocality_level_4";
  @SerializedName(SERIALIZED_NAME_SUBLOCALITY_LEVEL4)
  private String sublocalityLevel4;

  public static final String SERIALIZED_NAME_SUBLOCALITY_LEVEL5 = "sublocality_level_5";
  @SerializedName(SERIALIZED_NAME_SUBLOCALITY_LEVEL5)
  private String sublocalityLevel5;

  public static final String SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL1 = "administrative_area_level_1";
  @SerializedName(SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL1)
  private String administrativeAreaLevel1;

  public static final String SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL2 = "administrative_area_level_2";
  @SerializedName(SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL2)
  private String administrativeAreaLevel2;

  public static final String SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL3 = "administrative_area_level_3";
  @SerializedName(SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL3)
  private String administrativeAreaLevel3;

  public static final String SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL4 = "administrative_area_level_4";
  @SerializedName(SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL4)
  private String administrativeAreaLevel4;

  public static final String SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL5 = "administrative_area_level_5";
  @SerializedName(SERIALIZED_NAME_ADMINISTRATIVE_AREA_LEVEL5)
  private String administrativeAreaLevel5;

  public static final String SERIALIZED_NAME_STATE_CODE = "state_code";
  @SerializedName(SERIALIZED_NAME_STATE_CODE)
  private String stateCode;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "country_code";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private InlineResponse2001GeoLocation location;

  public static final String SERIALIZED_NAME_PLACE_ID = "place_id";
  @SerializedName(SERIALIZED_NAME_PLACE_ID)
  private String placeId;

  public InlineResponse2001Geo() { 
  }

  public InlineResponse2001Geo language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * The language of the localizable fields ot this geographical information set.&lt;p&gt;Please note that beside the general restrictions listed below only languages configured during system setup for your respective tenant are allowed.&lt;/p&gt;&lt;p&gt;See also &lt;a href&#x3D;\&quot;#isolanguage-codes\&quot;&gt;in the appendix&lt;/a&gt;.&lt;/p&gt;
   * @return language
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "de", required = true, value = "The language of the localizable fields ot this geographical information set.<p>Please note that beside the general restrictions listed below only languages configured during system setup for your respective tenant are allowed.</p><p>See also <a href=\"#isolanguage-codes\">in the appendix</a>.</p>")

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public InlineResponse2001Geo formattedAddress(String formattedAddress) {
    
    this.formattedAddress = formattedAddress;
    return this;
  }

   /**
   * The formatted address in the local format of the properties location.
   * @return formattedAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Nordhedig 20, 25980 Sylt, Germany", required = true, value = "The formatted address in the local format of the properties location.")

  public String getFormattedAddress() {
    return formattedAddress;
  }


  public void setFormattedAddress(String formattedAddress) {
    this.formattedAddress = formattedAddress;
  }


  public InlineResponse2001Geo route(String route) {
    
    this.route = route;
    return this;
  }

   /**
   * The name of the route or street.
   * @return route
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Nordhedig", value = "The name of the route or street.")

  public String getRoute() {
    return route;
  }


  public void setRoute(String route) {
    this.route = route;
  }


  public InlineResponse2001Geo streetNumber(String streetNumber) {
    
    this.streetNumber = streetNumber;
    return this;
  }

   /**
   * The number of the street.
   * @return streetNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20", value = "The number of the street.")

  public String getStreetNumber() {
    return streetNumber;
  }


  public void setStreetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
  }


  public InlineResponse2001Geo postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The postal code of the location.
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25980", value = "The postal code of the location.")

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public InlineResponse2001Geo locality(String locality) {
    
    this.locality = locality;
    return this;
  }

   /**
   * A city or town.
   * @return locality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sylt", value = "A city or town.")

  public String getLocality() {
    return locality;
  }


  public void setLocality(String locality) {
    this.locality = locality;
  }


  public InlineResponse2001Geo sublocality(String sublocality) {
    
    this.sublocality = sublocality;
    return this;
  }

   /**
   * A smaller area within a locality.
   * @return sublocality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Westerland", value = "A smaller area within a locality.")

  public String getSublocality() {
    return sublocality;
  }


  public void setSublocality(String sublocality) {
    this.sublocality = sublocality;
  }


  public InlineResponse2001Geo sublocalityLevel1(String sublocalityLevel1) {
    
    this.sublocalityLevel1 = sublocalityLevel1;
    return this;
  }

   /**
   * A smaller area within a locality at level 1.
   * @return sublocalityLevel1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Westerland", value = "A smaller area within a locality at level 1.")

  public String getSublocalityLevel1() {
    return sublocalityLevel1;
  }


  public void setSublocalityLevel1(String sublocalityLevel1) {
    this.sublocalityLevel1 = sublocalityLevel1;
  }


  public InlineResponse2001Geo sublocalityLevel2(String sublocalityLevel2) {
    
    this.sublocalityLevel2 = sublocalityLevel2;
    return this;
  }

   /**
   * A smaller area within a locality at level 2.
   * @return sublocalityLevel2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Some Sublocality", value = "A smaller area within a locality at level 2.")

  public String getSublocalityLevel2() {
    return sublocalityLevel2;
  }


  public void setSublocalityLevel2(String sublocalityLevel2) {
    this.sublocalityLevel2 = sublocalityLevel2;
  }


  public InlineResponse2001Geo sublocalityLevel3(String sublocalityLevel3) {
    
    this.sublocalityLevel3 = sublocalityLevel3;
    return this;
  }

   /**
   * A smaller area within a locality at level 3.
   * @return sublocalityLevel3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Some Sublocality", value = "A smaller area within a locality at level 3.")

  public String getSublocalityLevel3() {
    return sublocalityLevel3;
  }


  public void setSublocalityLevel3(String sublocalityLevel3) {
    this.sublocalityLevel3 = sublocalityLevel3;
  }


  public InlineResponse2001Geo sublocalityLevel4(String sublocalityLevel4) {
    
    this.sublocalityLevel4 = sublocalityLevel4;
    return this;
  }

   /**
   * A smaller area within a locality at level 4.
   * @return sublocalityLevel4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Some Sublocality", value = "A smaller area within a locality at level 4.")

  public String getSublocalityLevel4() {
    return sublocalityLevel4;
  }


  public void setSublocalityLevel4(String sublocalityLevel4) {
    this.sublocalityLevel4 = sublocalityLevel4;
  }


  public InlineResponse2001Geo sublocalityLevel5(String sublocalityLevel5) {
    
    this.sublocalityLevel5 = sublocalityLevel5;
    return this;
  }

   /**
   * A smaller area within a locality at level 5.
   * @return sublocalityLevel5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Some Sublocality", value = "A smaller area within a locality at level 5.")

  public String getSublocalityLevel5() {
    return sublocalityLevel5;
  }


  public void setSublocalityLevel5(String sublocalityLevel5) {
    this.sublocalityLevel5 = sublocalityLevel5;
  }


  public InlineResponse2001Geo administrativeAreaLevel1(String administrativeAreaLevel1) {
    
    this.administrativeAreaLevel1 = administrativeAreaLevel1;
    return this;
  }

   /**
   * A level 1 administrative area, such as a state or province.
   * @return administrativeAreaLevel1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Schleswig-Holstein", value = "A level 1 administrative area, such as a state or province.")

  public String getAdministrativeAreaLevel1() {
    return administrativeAreaLevel1;
  }


  public void setAdministrativeAreaLevel1(String administrativeAreaLevel1) {
    this.administrativeAreaLevel1 = administrativeAreaLevel1;
  }


  public InlineResponse2001Geo administrativeAreaLevel2(String administrativeAreaLevel2) {
    
    this.administrativeAreaLevel2 = administrativeAreaLevel2;
    return this;
  }

   /**
   * A level 2 administrative area.
   * @return administrativeAreaLevel2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Friesland", value = "A level 2 administrative area.")

  public String getAdministrativeAreaLevel2() {
    return administrativeAreaLevel2;
  }


  public void setAdministrativeAreaLevel2(String administrativeAreaLevel2) {
    this.administrativeAreaLevel2 = administrativeAreaLevel2;
  }


  public InlineResponse2001Geo administrativeAreaLevel3(String administrativeAreaLevel3) {
    
    this.administrativeAreaLevel3 = administrativeAreaLevel3;
    return this;
  }

   /**
   * A level 3 administrative area
   * @return administrativeAreaLevel3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A level 3 administrative area")

  public String getAdministrativeAreaLevel3() {
    return administrativeAreaLevel3;
  }


  public void setAdministrativeAreaLevel3(String administrativeAreaLevel3) {
    this.administrativeAreaLevel3 = administrativeAreaLevel3;
  }


  public InlineResponse2001Geo administrativeAreaLevel4(String administrativeAreaLevel4) {
    
    this.administrativeAreaLevel4 = administrativeAreaLevel4;
    return this;
  }

   /**
   * A level 4 administrative area.
   * @return administrativeAreaLevel4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A level 4 administrative area.")

  public String getAdministrativeAreaLevel4() {
    return administrativeAreaLevel4;
  }


  public void setAdministrativeAreaLevel4(String administrativeAreaLevel4) {
    this.administrativeAreaLevel4 = administrativeAreaLevel4;
  }


  public InlineResponse2001Geo administrativeAreaLevel5(String administrativeAreaLevel5) {
    
    this.administrativeAreaLevel5 = administrativeAreaLevel5;
    return this;
  }

   /**
   * A level 5 administrative area
   * @return administrativeAreaLevel5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A level 5 administrative area")

  public String getAdministrativeAreaLevel5() {
    return administrativeAreaLevel5;
  }


  public void setAdministrativeAreaLevel5(String administrativeAreaLevel5) {
    this.administrativeAreaLevel5 = administrativeAreaLevel5;
  }


  public InlineResponse2001Geo stateCode(String stateCode) {
    
    this.stateCode = stateCode;
    return this;
  }

   /**
   * The state or province code for the administrative area.
   * @return stateCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "SH", value = "The state or province code for the administrative area.")

  public String getStateCode() {
    return stateCode;
  }


  public void setStateCode(String stateCode) {
    this.stateCode = stateCode;
  }


  public InlineResponse2001Geo country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * The country of this geographical information set.
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Germany", value = "The country of this geographical information set.")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public InlineResponse2001Geo countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The country code for the country.
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DE", value = "The country code for the country.")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public InlineResponse2001Geo location(InlineResponse2001GeoLocation location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public InlineResponse2001GeoLocation getLocation() {
    return location;
  }


  public void setLocation(InlineResponse2001GeoLocation location) {
    this.location = location;
  }


  public InlineResponse2001Geo placeId(String placeId) {
    
    this.placeId = placeId;
    return this;
  }

   /**
   * Uniquely identifies a place in our database.
   * @return placeId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "ChIJVaxqTevetEcRyfs8PGHK6mw", required = true, value = "Uniquely identifies a place in our database.")

  public String getPlaceId() {
    return placeId;
  }


  public void setPlaceId(String placeId) {
    this.placeId = placeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Geo inlineResponse2001Geo = (InlineResponse2001Geo) o;
    return Objects.equals(this.language, inlineResponse2001Geo.language) &&
        Objects.equals(this.formattedAddress, inlineResponse2001Geo.formattedAddress) &&
        Objects.equals(this.route, inlineResponse2001Geo.route) &&
        Objects.equals(this.streetNumber, inlineResponse2001Geo.streetNumber) &&
        Objects.equals(this.postalCode, inlineResponse2001Geo.postalCode) &&
        Objects.equals(this.locality, inlineResponse2001Geo.locality) &&
        Objects.equals(this.sublocality, inlineResponse2001Geo.sublocality) &&
        Objects.equals(this.sublocalityLevel1, inlineResponse2001Geo.sublocalityLevel1) &&
        Objects.equals(this.sublocalityLevel2, inlineResponse2001Geo.sublocalityLevel2) &&
        Objects.equals(this.sublocalityLevel3, inlineResponse2001Geo.sublocalityLevel3) &&
        Objects.equals(this.sublocalityLevel4, inlineResponse2001Geo.sublocalityLevel4) &&
        Objects.equals(this.sublocalityLevel5, inlineResponse2001Geo.sublocalityLevel5) &&
        Objects.equals(this.administrativeAreaLevel1, inlineResponse2001Geo.administrativeAreaLevel1) &&
        Objects.equals(this.administrativeAreaLevel2, inlineResponse2001Geo.administrativeAreaLevel2) &&
        Objects.equals(this.administrativeAreaLevel3, inlineResponse2001Geo.administrativeAreaLevel3) &&
        Objects.equals(this.administrativeAreaLevel4, inlineResponse2001Geo.administrativeAreaLevel4) &&
        Objects.equals(this.administrativeAreaLevel5, inlineResponse2001Geo.administrativeAreaLevel5) &&
        Objects.equals(this.stateCode, inlineResponse2001Geo.stateCode) &&
        Objects.equals(this.country, inlineResponse2001Geo.country) &&
        Objects.equals(this.countryCode, inlineResponse2001Geo.countryCode) &&
        Objects.equals(this.location, inlineResponse2001Geo.location) &&
        Objects.equals(this.placeId, inlineResponse2001Geo.placeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, formattedAddress, route, streetNumber, postalCode, locality, sublocality, sublocalityLevel1, sublocalityLevel2, sublocalityLevel3, sublocalityLevel4, sublocalityLevel5, administrativeAreaLevel1, administrativeAreaLevel2, administrativeAreaLevel3, administrativeAreaLevel4, administrativeAreaLevel5, stateCode, country, countryCode, location, placeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Geo {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    formattedAddress: ").append(toIndentedString(formattedAddress)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("    streetNumber: ").append(toIndentedString(streetNumber)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    sublocality: ").append(toIndentedString(sublocality)).append("\n");
    sb.append("    sublocalityLevel1: ").append(toIndentedString(sublocalityLevel1)).append("\n");
    sb.append("    sublocalityLevel2: ").append(toIndentedString(sublocalityLevel2)).append("\n");
    sb.append("    sublocalityLevel3: ").append(toIndentedString(sublocalityLevel3)).append("\n");
    sb.append("    sublocalityLevel4: ").append(toIndentedString(sublocalityLevel4)).append("\n");
    sb.append("    sublocalityLevel5: ").append(toIndentedString(sublocalityLevel5)).append("\n");
    sb.append("    administrativeAreaLevel1: ").append(toIndentedString(administrativeAreaLevel1)).append("\n");
    sb.append("    administrativeAreaLevel2: ").append(toIndentedString(administrativeAreaLevel2)).append("\n");
    sb.append("    administrativeAreaLevel3: ").append(toIndentedString(administrativeAreaLevel3)).append("\n");
    sb.append("    administrativeAreaLevel4: ").append(toIndentedString(administrativeAreaLevel4)).append("\n");
    sb.append("    administrativeAreaLevel5: ").append(toIndentedString(administrativeAreaLevel5)).append("\n");
    sb.append("    stateCode: ").append(toIndentedString(stateCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    placeId: ").append(toIndentedString(placeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

