/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.lodgea.JSON;

/**
 * Further information regarding the facility.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-06T17:11:31.294726198Z[Etc/UTC]")
public class PropertiesPropertyIdGet200ResponsePropertyFacilityInfo {
  public static final String SERIALIZED_NAME_GUEST_ROOM_LIST = "guestRoomList";
  @SerializedName(SERIALIZED_NAME_GUEST_ROOM_LIST)
  private List<PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner> guestRoomList = new ArrayList<>();

  public PropertiesPropertyIdGet200ResponsePropertyFacilityInfo() {
  }

  public PropertiesPropertyIdGet200ResponsePropertyFacilityInfo guestRoomList(List<PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner> guestRoomList) {
    
    this.guestRoomList = guestRoomList;
    return this;
  }

  public PropertiesPropertyIdGet200ResponsePropertyFacilityInfo addGuestRoomListItem(PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner guestRoomListItem) {
    this.guestRoomList.add(guestRoomListItem);
    return this;
  }

   /**
   * An array of objects representing a room in the property.
   * @return guestRoomList
  **/
  @javax.annotation.Nonnull

  public List<PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner> getGuestRoomList() {
    return guestRoomList;
  }


  public void setGuestRoomList(List<PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner> guestRoomList) {
    this.guestRoomList = guestRoomList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertiesPropertyIdGet200ResponsePropertyFacilityInfo propertiesPropertyIdGet200ResponsePropertyFacilityInfo = (PropertiesPropertyIdGet200ResponsePropertyFacilityInfo) o;
    return Objects.equals(this.guestRoomList, propertiesPropertyIdGet200ResponsePropertyFacilityInfo.guestRoomList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guestRoomList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertiesPropertyIdGet200ResponsePropertyFacilityInfo {\n");
    sb.append("    guestRoomList: ").append(toIndentedString(guestRoomList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("guestRoomList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("guestRoomList");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PropertiesPropertyIdGet200ResponsePropertyFacilityInfo
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PropertiesPropertyIdGet200ResponsePropertyFacilityInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PropertiesPropertyIdGet200ResponsePropertyFacilityInfo is not found in the empty JSON string", PropertiesPropertyIdGet200ResponsePropertyFacilityInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PropertiesPropertyIdGet200ResponsePropertyFacilityInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PropertiesPropertyIdGet200ResponsePropertyFacilityInfo` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PropertiesPropertyIdGet200ResponsePropertyFacilityInfo.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("guestRoomList").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `guestRoomList` to be an array in the JSON string but got `%s`", jsonObj.get("guestRoomList").toString()));
      }

      JsonArray jsonArrayguestRoomList = jsonObj.getAsJsonArray("guestRoomList");
      // validate the required field `guestRoomList` (array)
      for (int i = 0; i < jsonArrayguestRoomList.size(); i++) {
        PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner.validateJsonObject(jsonArrayguestRoomList.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PropertiesPropertyIdGet200ResponsePropertyFacilityInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PropertiesPropertyIdGet200ResponsePropertyFacilityInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PropertiesPropertyIdGet200ResponsePropertyFacilityInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PropertiesPropertyIdGet200ResponsePropertyFacilityInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<PropertiesPropertyIdGet200ResponsePropertyFacilityInfo>() {
           @Override
           public void write(JsonWriter out, PropertiesPropertyIdGet200ResponsePropertyFacilityInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PropertiesPropertyIdGet200ResponsePropertyFacilityInfo read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PropertiesPropertyIdGet200ResponsePropertyFacilityInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PropertiesPropertyIdGet200ResponsePropertyFacilityInfo
  * @throws IOException if the JSON string is invalid with respect to PropertiesPropertyIdGet200ResponsePropertyFacilityInfo
  */
  public static PropertiesPropertyIdGet200ResponsePropertyFacilityInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PropertiesPropertyIdGet200ResponsePropertyFacilityInfo.class);
  }

 /**
  * Convert an instance of PropertiesPropertyIdGet200ResponsePropertyFacilityInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

