/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.lodgea.JSON;

/**
 * PropertiesPropertyIdAvailabilityGet200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-06T17:11:31.294726198Z[Etc/UTC]")
public class PropertiesPropertyIdAvailabilityGet200Response {
  public static final String SERIALIZED_NAME_AVAILABILITY_LIST = "availabilityList";
  @SerializedName(SERIALIZED_NAME_AVAILABILITY_LIST)
  private List<PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner> availabilityList = new ArrayList<>();

  public PropertiesPropertyIdAvailabilityGet200Response() {
  }

  public PropertiesPropertyIdAvailabilityGet200Response availabilityList(List<PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner> availabilityList) {
    
    this.availabilityList = availabilityList;
    return this;
  }

  public PropertiesPropertyIdAvailabilityGet200Response addAvailabilityListItem(PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner availabilityListItem) {
    this.availabilityList.add(availabilityListItem);
    return this;
  }

   /**
   * An array of objects describing the available booking options.
   * @return availabilityList
  **/
  @javax.annotation.Nonnull

  public List<PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner> getAvailabilityList() {
    return availabilityList;
  }


  public void setAvailabilityList(List<PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner> availabilityList) {
    this.availabilityList = availabilityList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertiesPropertyIdAvailabilityGet200Response propertiesPropertyIdAvailabilityGet200Response = (PropertiesPropertyIdAvailabilityGet200Response) o;
    return Objects.equals(this.availabilityList, propertiesPropertyIdAvailabilityGet200Response.availabilityList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availabilityList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertiesPropertyIdAvailabilityGet200Response {\n");
    sb.append("    availabilityList: ").append(toIndentedString(availabilityList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("availabilityList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("availabilityList");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PropertiesPropertyIdAvailabilityGet200Response
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PropertiesPropertyIdAvailabilityGet200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PropertiesPropertyIdAvailabilityGet200Response is not found in the empty JSON string", PropertiesPropertyIdAvailabilityGet200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PropertiesPropertyIdAvailabilityGet200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PropertiesPropertyIdAvailabilityGet200Response` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PropertiesPropertyIdAvailabilityGet200Response.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("availabilityList").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `availabilityList` to be an array in the JSON string but got `%s`", jsonObj.get("availabilityList").toString()));
      }

      JsonArray jsonArrayavailabilityList = jsonObj.getAsJsonArray("availabilityList");
      // validate the required field `availabilityList` (array)
      for (int i = 0; i < jsonArrayavailabilityList.size(); i++) {
        PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner.validateJsonObject(jsonArrayavailabilityList.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PropertiesPropertyIdAvailabilityGet200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PropertiesPropertyIdAvailabilityGet200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PropertiesPropertyIdAvailabilityGet200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PropertiesPropertyIdAvailabilityGet200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<PropertiesPropertyIdAvailabilityGet200Response>() {
           @Override
           public void write(JsonWriter out, PropertiesPropertyIdAvailabilityGet200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PropertiesPropertyIdAvailabilityGet200Response read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PropertiesPropertyIdAvailabilityGet200Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PropertiesPropertyIdAvailabilityGet200Response
  * @throws IOException if the JSON string is invalid with respect to PropertiesPropertyIdAvailabilityGet200Response
  */
  public static PropertiesPropertyIdAvailabilityGet200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PropertiesPropertyIdAvailabilityGet200Response.class);
  }

 /**
  * Convert an instance of PropertiesPropertyIdAvailabilityGet200Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

