/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.lodgea.JSON;

/**
 * PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-06T17:11:31.294726198Z[Etc/UTC]")
public class PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner {
  public static final String SERIALIZED_NAME_PERCENT_AFTER_RESERVATION = "percentAfterReservation";
  @SerializedName(SERIALIZED_NAME_PERCENT_AFTER_RESERVATION)
  private BigDecimal percentAfterReservation;

  public static final String SERIALIZED_NAME_NIGHTS_AFTER_RESERVATION = "nightsAfterReservation";
  @SerializedName(SERIALIZED_NAME_NIGHTS_AFTER_RESERVATION)
  private BigDecimal nightsAfterReservation;

  public static final String SERIALIZED_NAME_DEADLINE_DAYS = "deadlineDays";
  @SerializedName(SERIALIZED_NAME_DEADLINE_DAYS)
  private BigDecimal deadlineDays;

  public static final String SERIALIZED_NAME_DEADLINE_HOURS = "deadlineHours";
  @SerializedName(SERIALIZED_NAME_DEADLINE_HOURS)
  private BigDecimal deadlineHours;

  public static final String SERIALIZED_NAME_PERCENT_AFTER_DEADLINE = "percentAfterDeadline";
  @SerializedName(SERIALIZED_NAME_PERCENT_AFTER_DEADLINE)
  private BigDecimal percentAfterDeadline;

  public static final String SERIALIZED_NAME_NIGHTS_AFTER_DEADLINE = "nightsAfterDeadline";
  @SerializedName(SERIALIZED_NAME_NIGHTS_AFTER_DEADLINE)
  private BigDecimal nightsAfterDeadline;

  public static final String SERIALIZED_NAME_NO_SHOW_POLICY = "noShowPolicy";
  @SerializedName(SERIALIZED_NAME_NO_SHOW_POLICY)
  private String noShowPolicy;

  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner() {
  }

  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner percentAfterReservation(BigDecimal percentAfterReservation) {
    
    this.percentAfterReservation = percentAfterReservation;
    return this;
  }

   /**
   * Percentage of refund after reservation.
   * @return percentAfterReservation
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPercentAfterReservation() {
    return percentAfterReservation;
  }


  public void setPercentAfterReservation(BigDecimal percentAfterReservation) {
    this.percentAfterReservation = percentAfterReservation;
  }


  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner nightsAfterReservation(BigDecimal nightsAfterReservation) {
    
    this.nightsAfterReservation = nightsAfterReservation;
    return this;
  }

   /**
   * Number of nights after reservation.
   * @return nightsAfterReservation
  **/
  @javax.annotation.Nonnull

  public BigDecimal getNightsAfterReservation() {
    return nightsAfterReservation;
  }


  public void setNightsAfterReservation(BigDecimal nightsAfterReservation) {
    this.nightsAfterReservation = nightsAfterReservation;
  }


  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner deadlineDays(BigDecimal deadlineDays) {
    
    this.deadlineDays = deadlineDays;
    return this;
  }

   /**
   * Deadline in days.
   * @return deadlineDays
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDeadlineDays() {
    return deadlineDays;
  }


  public void setDeadlineDays(BigDecimal deadlineDays) {
    this.deadlineDays = deadlineDays;
  }


  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner deadlineHours(BigDecimal deadlineHours) {
    
    this.deadlineHours = deadlineHours;
    return this;
  }

   /**
   * Deadline in hours.
   * @return deadlineHours
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDeadlineHours() {
    return deadlineHours;
  }


  public void setDeadlineHours(BigDecimal deadlineHours) {
    this.deadlineHours = deadlineHours;
  }


  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner percentAfterDeadline(BigDecimal percentAfterDeadline) {
    
    this.percentAfterDeadline = percentAfterDeadline;
    return this;
  }

   /**
   * Percentage of refund after deadline.
   * @return percentAfterDeadline
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPercentAfterDeadline() {
    return percentAfterDeadline;
  }


  public void setPercentAfterDeadline(BigDecimal percentAfterDeadline) {
    this.percentAfterDeadline = percentAfterDeadline;
  }


  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner nightsAfterDeadline(BigDecimal nightsAfterDeadline) {
    
    this.nightsAfterDeadline = nightsAfterDeadline;
    return this;
  }

   /**
   * Number of nights after deadline.
   * @return nightsAfterDeadline
  **/
  @javax.annotation.Nonnull

  public BigDecimal getNightsAfterDeadline() {
    return nightsAfterDeadline;
  }


  public void setNightsAfterDeadline(BigDecimal nightsAfterDeadline) {
    this.nightsAfterDeadline = nightsAfterDeadline;
  }


  public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner noShowPolicy(String noShowPolicy) {
    
    this.noShowPolicy = noShowPolicy;
    return this;
  }

   /**
   * No-show policy
   * @return noShowPolicy
  **/
  @javax.annotation.Nonnull

  public String getNoShowPolicy() {
    return noShowPolicy;
  }


  public void setNoShowPolicy(String noShowPolicy) {
    this.noShowPolicy = noShowPolicy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner = (PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner) o;
    return Objects.equals(this.percentAfterReservation, propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.percentAfterReservation) &&
        Objects.equals(this.nightsAfterReservation, propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.nightsAfterReservation) &&
        Objects.equals(this.deadlineDays, propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.deadlineDays) &&
        Objects.equals(this.deadlineHours, propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.deadlineHours) &&
        Objects.equals(this.percentAfterDeadline, propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.percentAfterDeadline) &&
        Objects.equals(this.nightsAfterDeadline, propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.nightsAfterDeadline) &&
        Objects.equals(this.noShowPolicy, propertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.noShowPolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(percentAfterReservation, nightsAfterReservation, deadlineDays, deadlineHours, percentAfterDeadline, nightsAfterDeadline, noShowPolicy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner {\n");
    sb.append("    percentAfterReservation: ").append(toIndentedString(percentAfterReservation)).append("\n");
    sb.append("    nightsAfterReservation: ").append(toIndentedString(nightsAfterReservation)).append("\n");
    sb.append("    deadlineDays: ").append(toIndentedString(deadlineDays)).append("\n");
    sb.append("    deadlineHours: ").append(toIndentedString(deadlineHours)).append("\n");
    sb.append("    percentAfterDeadline: ").append(toIndentedString(percentAfterDeadline)).append("\n");
    sb.append("    nightsAfterDeadline: ").append(toIndentedString(nightsAfterDeadline)).append("\n");
    sb.append("    noShowPolicy: ").append(toIndentedString(noShowPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("percentAfterReservation");
    openapiFields.add("nightsAfterReservation");
    openapiFields.add("deadlineDays");
    openapiFields.add("deadlineHours");
    openapiFields.add("percentAfterDeadline");
    openapiFields.add("nightsAfterDeadline");
    openapiFields.add("noShowPolicy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("percentAfterReservation");
    openapiRequiredFields.add("nightsAfterReservation");
    openapiRequiredFields.add("deadlineDays");
    openapiRequiredFields.add("deadlineHours");
    openapiRequiredFields.add("percentAfterDeadline");
    openapiRequiredFields.add("nightsAfterDeadline");
    openapiRequiredFields.add("noShowPolicy");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner is not found in the empty JSON string", PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("noShowPolicy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `noShowPolicy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("noShowPolicy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner>() {
           @Override
           public void write(JsonWriter out, PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner
  * @throws IOException if the JSON string is invalid with respect to PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner
  */
  public static PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner.class);
  }

 /**
  * Convert an instance of PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

