/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.lodgea.JSON;

/**
 * PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-06T17:11:31.294726198Z[Etc/UTC]")
public class PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner {
  public static final String SERIALIZED_NAME_DATE_TIME = "dateTime";
  @SerializedName(SERIALIZED_NAME_DATE_TIME)
  private BigDecimal dateTime;

  public static final String SERIALIZED_NAME_OCCUPANCY = "occupancy";
  @SerializedName(SERIALIZED_NAME_OCCUPANCY)
  private BigDecimal occupancy;

  public static final String SERIALIZED_NAME_PRICE_LIST = "priceList";
  @SerializedName(SERIALIZED_NAME_PRICE_LIST)
  private Map<String, BigDecimal> priceList = new HashMap<>();

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currencyCode";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner() {
  }

  public PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner dateTime(BigDecimal dateTime) {
    
    this.dateTime = dateTime;
    return this;
  }

   /**
   * The timestamp of the pricing information.
   * @return dateTime
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDateTime() {
    return dateTime;
  }


  public void setDateTime(BigDecimal dateTime) {
    this.dateTime = dateTime;
  }


  public PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner occupancy(BigDecimal occupancy) {
    
    this.occupancy = occupancy;
    return this;
  }

   /**
   * The number of occupants for which the pricing applies.
   * @return occupancy
  **/
  @javax.annotation.Nonnull

  public BigDecimal getOccupancy() {
    return occupancy;
  }


  public void setOccupancy(BigDecimal occupancy) {
    this.occupancy = occupancy;
  }


  public PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner priceList(Map<String, BigDecimal> priceList) {
    
    this.priceList = priceList;
    return this;
  }

  public PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner putPriceListItem(String key, BigDecimal priceListItem) {
    this.priceList.put(key, priceListItem);
    return this;
  }

   /**
   * A mapping of number of days of stay to prices.
   * @return priceList
  **/
  @javax.annotation.Nonnull

  public Map<String, BigDecimal> getPriceList() {
    return priceList;
  }


  public void setPriceList(Map<String, BigDecimal> priceList) {
    this.priceList = priceList;
  }


  public PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * The currency code for the prices.
   * @return currencyCode
  **/
  @javax.annotation.Nonnull

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner propertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner = (PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner) o;
    return Objects.equals(this.dateTime, propertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.dateTime) &&
        Objects.equals(this.occupancy, propertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.occupancy) &&
        Objects.equals(this.priceList, propertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.priceList) &&
        Objects.equals(this.currencyCode, propertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.currencyCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateTime, occupancy, priceList, currencyCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner {\n");
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    occupancy: ").append(toIndentedString(occupancy)).append("\n");
    sb.append("    priceList: ").append(toIndentedString(priceList)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dateTime");
    openapiFields.add("occupancy");
    openapiFields.add("priceList");
    openapiFields.add("currencyCode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("dateTime");
    openapiRequiredFields.add("occupancy");
    openapiRequiredFields.add("priceList");
    openapiRequiredFields.add("currencyCode");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner is not found in the empty JSON string", PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("currencyCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currencyCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currencyCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner>() {
           @Override
           public void write(JsonWriter out, PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner
  * @throws IOException if the JSON string is invalid with respect to PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner
  */
  public static PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner.class);
  }

 /**
  * Convert an instance of PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

