/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AvailablePropertiesInner1AttractionListInnerDistance
 */
public class AvailablePropertiesInner1AttractionListInnerDistanceTest {
    private final AvailablePropertiesInner1AttractionListInnerDistance model = new AvailablePropertiesInner1AttractionListInnerDistance();

    /**
     * Model tests for AvailablePropertiesInner1AttractionListInnerDistance
     */
    @Test
    public void testAvailablePropertiesInner1AttractionListInnerDistance() {
        // TODO: test AvailablePropertiesInner1AttractionListInnerDistance
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

}
