/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2003PropertyGuestInfo
 */
public class InlineResponse2003PropertyGuestInfoTest {
    private final InlineResponse2003PropertyGuestInfo model = new InlineResponse2003PropertyGuestInfo();

    /**
     * Model tests for InlineResponse2003PropertyGuestInfo
     */
    @Test
    public void testInlineResponse2003PropertyGuestInfo() {
        // TODO: test InlineResponse2003PropertyGuestInfo
    }

    /**
     * Test the property 'guestAddressRequired'
     */
    @Test
    public void guestAddressRequiredTest() {
        // TODO: test guestAddressRequired
    }

    /**
     * Test the property 'guestContactNumberRequired'
     */
    @Test
    public void guestContactNumberRequiredTest() {
        // TODO: test guestContactNumberRequired
    }

    /**
     * Test the property 'guestNameListRequired'
     */
    @Test
    public void guestNameListRequiredTest() {
        // TODO: test guestNameListRequired
    }

}
