/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2003PropertyGuaranteePolicy
 */
public class InlineResponse2003PropertyGuaranteePolicyTest {
    private final InlineResponse2003PropertyGuaranteePolicy model = new InlineResponse2003PropertyGuaranteePolicy();

    /**
     * Model tests for InlineResponse2003PropertyGuaranteePolicy
     */
    @Test
    public void testInlineResponse2003PropertyGuaranteePolicy() {
        // TODO: test InlineResponse2003PropertyGuaranteePolicy
    }

    /**
     * Test the property 'percentAfterReservation'
     */
    @Test
    public void percentAfterReservationTest() {
        // TODO: test percentAfterReservation
    }

    /**
     * Test the property 'nightsAfterReservation'
     */
    @Test
    public void nightsAfterReservationTest() {
        // TODO: test nightsAfterReservation
    }

    /**
     * Test the property 'deadlineDays'
     */
    @Test
    public void deadlineDaysTest() {
        // TODO: test deadlineDays
    }

    /**
     * Test the property 'deadlineHours'
     */
    @Test
    public void deadlineHoursTest() {
        // TODO: test deadlineHours
    }

    /**
     * Test the property 'percentAfterDeadline'
     */
    @Test
    public void percentAfterDeadlineTest() {
        // TODO: test percentAfterDeadline
    }

    /**
     * Test the property 'nightsAfterDeadline'
     */
    @Test
    public void nightsAfterDeadlineTest() {
        // TODO: test nightsAfterDeadline
    }

    /**
     * Test the property 'noShowPolicy'
     */
    @Test
    public void noShowPolicyTest() {
        // TODO: test noShowPolicy
    }

}
