/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.InlineResponse2001AttractionList;
import com.lodgea.model.InlineResponse2001Geo;
import com.lodgea.model.InlineResponse2001LowestPrice;
import com.lodgea.model.InlineResponse2001MediaList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2001List
 */
public class InlineResponse2001ListTest {
    private final InlineResponse2001List model = new InlineResponse2001List();

    /**
     * Model tests for InlineResponse2001List
     */
    @Test
    public void testInlineResponse2001List() {
        // TODO: test InlineResponse2001List
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'unitSystem'
     */
    @Test
    public void unitSystemTest() {
        // TODO: test unitSystem
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'serviceList'
     */
    @Test
    public void serviceListTest() {
        // TODO: test serviceList
    }

    /**
     * Test the property 'categoryList'
     */
    @Test
    public void categoryListTest() {
        // TODO: test categoryList
    }

    /**
     * Test the property 'uriPath'
     */
    @Test
    public void uriPathTest() {
        // TODO: test uriPath
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'geo'
     */
    @Test
    public void geoTest() {
        // TODO: test geo
    }

    /**
     * Test the property 'mediaList'
     */
    @Test
    public void mediaListTest() {
        // TODO: test mediaList
    }

    /**
     * Test the property 'attractionList'
     */
    @Test
    public void attractionListTest() {
        // TODO: test attractionList
    }

    /**
     * Test the property 'lowestPrice'
     */
    @Test
    public void lowestPriceTest() {
        // TODO: test lowestPrice
    }

}
