/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2001LowestPrice
 */
public class InlineResponse2001LowestPriceTest {
    private final InlineResponse2001LowestPrice model = new InlineResponse2001LowestPrice();

    /**
     * Model tests for InlineResponse2001LowestPrice
     */
    @Test
    public void testInlineResponse2001LowestPrice() {
        // TODO: test InlineResponse2001LowestPrice
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'arrivalDate'
     */
    @Test
    public void arrivalDateTest() {
        // TODO: test arrivalDate
    }

    /**
     * Test the property 'returnDate'
     */
    @Test
    public void returnDateTest() {
        // TODO: test returnDate
    }

    /**
     * Test the property 'lengthOfStay'
     */
    @Test
    public void lengthOfStayTest() {
        // TODO: test lengthOfStay
    }

}
