/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner
 */
public class PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInnerTest {
    private final PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner model = new PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner();

    /**
     * Model tests for PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner
     */
    @Test
    public void testPropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner() {
        // TODO: test PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner
    }

    /**
     * Test the property 'typeCode'
     */
    @Test
    public void typeCodeTest() {
        // TODO: test typeCode
    }

    /**
     * Test the property 'percent'
     */
    @Test
    public void percentTest() {
        // TODO: test percent
    }

    /**
     * Test the property 'chargeType'
     */
    @Test
    public void chargeTypeTest() {
        // TODO: test chargeType
    }

    /**
     * Test the property 'chargeFrequencyCode'
     */
    @Test
    public void chargeFrequencyCodeTest() {
        // TODO: test chargeFrequencyCode
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'conditionList'
     */
    @Test
    public void conditionListTest() {
        // TODO: test conditionList
    }

}
