/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.PropertiesGet200ResponseListInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PropertiesGet200Response
 */
public class PropertiesGet200ResponseTest {
    private final PropertiesGet200Response model = new PropertiesGet200Response();

    /**
     * Model tests for PropertiesGet200Response
     */
    @Test
    public void testPropertiesGet200Response() {
        // TODO: test PropertiesGet200Response
    }

    /**
     * Test the property '_list'
     */
    @Test
    public void _listTest() {
        // TODO: test _list
    }

    /**
     * Test the property 'pageToken'
     */
    @Test
    public void pageTokenTest() {
        // TODO: test pageToken
    }

}
