/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PropertiesPropertyIdGet200ResponsePropertyServiceListInner
 */
public class PropertiesPropertyIdGet200ResponsePropertyServiceListInnerTest {
    private final PropertiesPropertyIdGet200ResponsePropertyServiceListInner model = new PropertiesPropertyIdGet200ResponsePropertyServiceListInner();

    /**
     * Model tests for PropertiesPropertyIdGet200ResponsePropertyServiceListInner
     */
    @Test
    public void testPropertiesPropertyIdGet200ResponsePropertyServiceListInner() {
        // TODO: test PropertiesPropertyIdGet200ResponsePropertyServiceListInner
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'exists'
     */
    @Test
    public void existsTest() {
        // TODO: test exists
    }

    /**
     * Test the property 'included'
     */
    @Test
    public void includedTest() {
        // TODO: test included
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'featureList'
     */
    @Test
    public void featureListTest() {
        // TODO: test featureList
    }

    /**
     * Test the property 'typeList'
     */
    @Test
    public void typeListTest() {
        // TODO: test typeList
    }

    /**
     * Test the property 'itemList'
     */
    @Test
    public void itemListTest() {
        // TODO: test itemList
    }

    /**
     * Test the property 'operationTimeList'
     */
    @Test
    public void operationTimeListTest() {
        // TODO: test operationTimeList
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
