/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for V1AvailabilityGetPost200ResponseRoomTypeListInner
 */
public class V1AvailabilityGetPost200ResponseRoomTypeListInnerTest {
    private final V1AvailabilityGetPost200ResponseRoomTypeListInner model = new V1AvailabilityGetPost200ResponseRoomTypeListInner();

    /**
     * Model tests for V1AvailabilityGetPost200ResponseRoomTypeListInner
     */
    @Test
    public void testV1AvailabilityGetPost200ResponseRoomTypeListInner() {
        // TODO: test V1AvailabilityGetPost200ResponseRoomTypeListInner
    }

    /**
     * Test the property 'typeCode'
     */
    @Test
    public void typeCodeTest() {
        // TODO: test typeCode
    }

}
