/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for V1PropertyGetPost200ResponsePropertyPolicyListInnerTaxPolicyListInner
 */
public class V1PropertyGetPost200ResponsePropertyPolicyListInnerTaxPolicyListInnerTest {
    private final V1PropertyGetPost200ResponsePropertyPolicyListInnerTaxPolicyListInner model = new V1PropertyGetPost200ResponsePropertyPolicyListInnerTaxPolicyListInner();

    /**
     * Model tests for V1PropertyGetPost200ResponsePropertyPolicyListInnerTaxPolicyListInner
     */
    @Test
    public void testV1PropertyGetPost200ResponsePropertyPolicyListInnerTaxPolicyListInner() {
        // TODO: test V1PropertyGetPost200ResponsePropertyPolicyListInnerTaxPolicyListInner
    }

    /**
     * Test the property 'typeCode'
     */
    @Test
    public void typeCodeTest() {
        // TODO: test typeCode
    }

    /**
     * Test the property 'percent'
     */
    @Test
    public void percentTest() {
        // TODO: test percent
    }

    /**
     * Test the property 'chargeType'
     */
    @Test
    public void chargeTypeTest() {
        // TODO: test chargeType
    }

    /**
     * Test the property 'chargeFrequencyCode'
     */
    @Test
    public void chargeFrequencyCodeTest() {
        // TODO: test chargeFrequencyCode
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'conditionList'
     */
    @Test
    public void conditionListTest() {
        // TODO: test conditionList
    }

}
