/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for V1PropertyGetPost200ResponsePropertyPropertyInfoCategoryListInner
 */
public class V1PropertyGetPost200ResponsePropertyPropertyInfoCategoryListInnerTest {
    private final V1PropertyGetPost200ResponsePropertyPropertyInfoCategoryListInner model = new V1PropertyGetPost200ResponsePropertyPropertyInfoCategoryListInner();

    /**
     * Model tests for V1PropertyGetPost200ResponsePropertyPropertyInfoCategoryListInner
     */
    @Test
    public void testV1PropertyGetPost200ResponsePropertyPropertyInfoCategoryListInner() {
        // TODO: test V1PropertyGetPost200ResponsePropertyPropertyInfoCategoryListInner
    }

    /**
     * Test the property 'exists'
     */
    @Test
    public void existsTest() {
        // TODO: test exists
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
