/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for V1PropertyGetPost200ResponsePropertyGuestInfo
 */
public class V1PropertyGetPost200ResponsePropertyGuestInfoTest {
    private final V1PropertyGetPost200ResponsePropertyGuestInfo model = new V1PropertyGetPost200ResponsePropertyGuestInfo();

    /**
     * Model tests for V1PropertyGetPost200ResponsePropertyGuestInfo
     */
    @Test
    public void testV1PropertyGetPost200ResponsePropertyGuestInfo() {
        // TODO: test V1PropertyGetPost200ResponsePropertyGuestInfo
    }

    /**
     * Test the property 'guestAddressRequired'
     */
    @Test
    public void guestAddressRequiredTest() {
        // TODO: test guestAddressRequired
    }

    /**
     * Test the property 'guestContactNumberRequired'
     */
    @Test
    public void guestContactNumberRequiredTest() {
        // TODO: test guestContactNumberRequired
    }

    /**
     * Test the property 'guestNameListRequired'
     */
    @Test
    public void guestNameListRequiredTest() {
        // TODO: test guestNameListRequired
    }

}
