/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInner
 */
public class V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerTest {
    private final V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInner model = new V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInner();

    /**
     * Model tests for V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInner
     */
    @Test
    public void testV1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInner() {
        // TODO: test V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInner
    }

    /**
     * Test the property 'dateTime'
     */
    @Test
    public void dateTimeTest() {
        // TODO: test dateTime
    }

    /**
     * Test the property 'occupancy'
     */
    @Test
    public void occupancyTest() {
        // TODO: test occupancy
    }

    /**
     * Test the property 'priceList'
     */
    @Test
    public void priceListTest() {
        // TODO: test priceList
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

}
