/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lodgea.model.V1PropertyGetPost200ResponsePropertyTransactionExternalListInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for V1PropertyGetPost200ResponsePropertyTransaction
 */
public class V1PropertyGetPost200ResponsePropertyTransactionTest {
    private final V1PropertyGetPost200ResponsePropertyTransaction model = new V1PropertyGetPost200ResponsePropertyTransaction();

    /**
     * Model tests for V1PropertyGetPost200ResponsePropertyTransaction
     */
    @Test
    public void testV1PropertyGetPost200ResponsePropertyTransaction() {
        // TODO: test V1PropertyGetPost200ResponsePropertyTransaction
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'contactTypeList'
     */
    @Test
    public void contactTypeListTest() {
        // TODO: test contactTypeList
    }

    /**
     * Test the property 'externalList'
     */
    @Test
    public void externalListTest() {
        // TODO: test externalList
    }

}
