/*
 * lodgea-java
 * LODGEA SDK for java. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.controllers;

import com.lodgea.ApiCallback;
import com.lodgea.ApiClient;
import com.lodgea.ApiException;
import com.lodgea.ApiResponse;
import com.lodgea.Configuration;
import com.lodgea.Pair;
import com.lodgea.ProgressRequestBody;
import com.lodgea.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.lodgea.model.InlineObject;
import com.lodgea.model.InlineObject1;
import com.lodgea.model.InlineResponse200;
import com.lodgea.model.InlineResponse2001;
import com.lodgea.model.InlineResponse2002;
import com.lodgea.model.InlineResponse2003;
import com.lodgea.model.InlineResponse2004;
import com.lodgea.model.InlineResponse400;
import com.lodgea.model.InlineResponse4001;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for availabilitySearchPost
     * @param inlineObject1  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of available properties matching the given criteria is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call availabilitySearchPostCall(InlineObject1 inlineObject1, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = inlineObject1;

        // create path and map variables
        String localVarPath = "/availability/search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call availabilitySearchPostValidateBeforeCall(InlineObject1 inlineObject1, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = availabilitySearchPostCall(inlineObject1, _callback);
        return localVarCall;

    }

    /**
     * Search for availability
     * Get availability information based on search criteria.
     * @param inlineObject1  (optional)
     * @return InlineResponse2001
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of available properties matching the given criteria is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse2001 availabilitySearchPost(InlineObject1 inlineObject1) throws ApiException {
        ApiResponse<InlineResponse2001> localVarResp = availabilitySearchPostWithHttpInfo(inlineObject1);
        return localVarResp.getData();
    }

    /**
     * Search for availability
     * Get availability information based on search criteria.
     * @param inlineObject1  (optional)
     * @return ApiResponse&lt;InlineResponse2001&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of available properties matching the given criteria is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse2001> availabilitySearchPostWithHttpInfo(InlineObject1 inlineObject1) throws ApiException {
        okhttp3.Call localVarCall = availabilitySearchPostValidateBeforeCall(inlineObject1, null);
        Type localVarReturnType = new TypeToken<InlineResponse2001>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Search for availability (asynchronously)
     * Get availability information based on search criteria.
     * @param inlineObject1  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of available properties matching the given criteria is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call availabilitySearchPostAsync(InlineObject1 inlineObject1, final ApiCallback<InlineResponse2001> _callback) throws ApiException {

        okhttp3.Call localVarCall = availabilitySearchPostValidateBeforeCall(inlineObject1, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse2001>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for locationSearchPost
     * @param inlineObject  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of locations matching the given location search text is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call locationSearchPostCall(InlineObject inlineObject, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = inlineObject;

        // create path and map variables
        String localVarPath = "/location/search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call locationSearchPostValidateBeforeCall(InlineObject inlineObject, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = locationSearchPostCall(inlineObject, _callback);
        return localVarCall;

    }

    /**
     * Search for location
     * Get a list of locations and their lowest available rate related to a given keyword.
     * @param inlineObject  (optional)
     * @return InlineResponse200
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of locations matching the given location search text is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse200 locationSearchPost(InlineObject inlineObject) throws ApiException {
        ApiResponse<InlineResponse200> localVarResp = locationSearchPostWithHttpInfo(inlineObject);
        return localVarResp.getData();
    }

    /**
     * Search for location
     * Get a list of locations and their lowest available rate related to a given keyword.
     * @param inlineObject  (optional)
     * @return ApiResponse&lt;InlineResponse200&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of locations matching the given location search text is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse200> locationSearchPostWithHttpInfo(InlineObject inlineObject) throws ApiException {
        okhttp3.Call localVarCall = locationSearchPostValidateBeforeCall(inlineObject, null);
        Type localVarReturnType = new TypeToken<InlineResponse200>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Search for location (asynchronously)
     * Get a list of locations and their lowest available rate related to a given keyword.
     * @param inlineObject  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of locations matching the given location search text is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call locationSearchPostAsync(InlineObject inlineObject, final ApiCallback<InlineResponse200> _callback) throws ApiException {

        okhttp3.Call localVarCall = locationSearchPostValidateBeforeCall(inlineObject, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse200>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for propertiesGet
     * @param keyword  (optional)
     * @param pageToken  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call propertiesGetCall(String keyword, String pageToken, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/properties";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (keyword != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("keyword", keyword));
        }

        if (pageToken != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageToken", pageToken));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call propertiesGetValidateBeforeCall(String keyword, String pageToken, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = propertiesGetCall(keyword, pageToken, _callback);
        return localVarCall;

    }

    /**
     * List (filtered) properties
     * List properties, optionally filtered by a keyword.
     * @param keyword  (optional)
     * @param pageToken  (optional)
     * @return InlineResponse2002
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse2002 propertiesGet(String keyword, String pageToken) throws ApiException {
        ApiResponse<InlineResponse2002> localVarResp = propertiesGetWithHttpInfo(keyword, pageToken);
        return localVarResp.getData();
    }

    /**
     * List (filtered) properties
     * List properties, optionally filtered by a keyword.
     * @param keyword  (optional)
     * @param pageToken  (optional)
     * @return ApiResponse&lt;InlineResponse2002&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse2002> propertiesGetWithHttpInfo(String keyword, String pageToken) throws ApiException {
        okhttp3.Call localVarCall = propertiesGetValidateBeforeCall(keyword, pageToken, null);
        Type localVarReturnType = new TypeToken<InlineResponse2002>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List (filtered) properties (asynchronously)
     * List properties, optionally filtered by a keyword.
     * @param keyword  (optional)
     * @param pageToken  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call propertiesGetAsync(String keyword, String pageToken, final ApiCallback<InlineResponse2002> _callback) throws ApiException {

        okhttp3.Call localVarCall = propertiesGetValidateBeforeCall(keyword, pageToken, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse2002>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for propertiesPropertyIdAvailabilityGet
     * @param propertyId  (required)
     * @param currencyCode  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call propertiesPropertyIdAvailabilityGetCall(String propertyId, String currencyCode, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/properties/{propertyId}/availability"
            .replaceAll("\\{" + "propertyId" + "\\}", localVarApiClient.escapeString(propertyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (currencyCode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("currencyCode", currencyCode));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call propertiesPropertyIdAvailabilityGetValidateBeforeCall(String propertyId, String currencyCode, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'propertyId' is set
        if (propertyId == null) {
            throw new ApiException("Missing the required parameter 'propertyId' when calling propertiesPropertyIdAvailabilityGet(Async)");
        }
        
        // verify the required parameter 'currencyCode' is set
        if (currencyCode == null) {
            throw new ApiException("Missing the required parameter 'currencyCode' when calling propertiesPropertyIdAvailabilityGet(Async)");
        }
        

        okhttp3.Call localVarCall = propertiesPropertyIdAvailabilityGetCall(propertyId, currencyCode, _callback);
        return localVarCall;

    }

    /**
     * Get a properties availability
     * Get detailed availability information for a specific property.
     * @param propertyId  (required)
     * @param currencyCode  (required)
     * @return InlineResponse2004
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse2004 propertiesPropertyIdAvailabilityGet(String propertyId, String currencyCode) throws ApiException {
        ApiResponse<InlineResponse2004> localVarResp = propertiesPropertyIdAvailabilityGetWithHttpInfo(propertyId, currencyCode);
        return localVarResp.getData();
    }

    /**
     * Get a properties availability
     * Get detailed availability information for a specific property.
     * @param propertyId  (required)
     * @param currencyCode  (required)
     * @return ApiResponse&lt;InlineResponse2004&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse2004> propertiesPropertyIdAvailabilityGetWithHttpInfo(String propertyId, String currencyCode) throws ApiException {
        okhttp3.Call localVarCall = propertiesPropertyIdAvailabilityGetValidateBeforeCall(propertyId, currencyCode, null);
        Type localVarReturnType = new TypeToken<InlineResponse2004>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a properties availability (asynchronously)
     * Get detailed availability information for a specific property.
     * @param propertyId  (required)
     * @param currencyCode  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, a list of properties matching the given keyword is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call propertiesPropertyIdAvailabilityGetAsync(String propertyId, String currencyCode, final ApiCallback<InlineResponse2004> _callback) throws ApiException {

        okhttp3.Call localVarCall = propertiesPropertyIdAvailabilityGetValidateBeforeCall(propertyId, currencyCode, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse2004>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for propertiesPropertyIdGet
     * @param propertyId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, property found, the whole property object is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call propertiesPropertyIdGetCall(String propertyId, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/properties/{propertyId}"
            .replaceAll("\\{" + "propertyId" + "\\}", localVarApiClient.escapeString(propertyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call propertiesPropertyIdGetValidateBeforeCall(String propertyId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'propertyId' is set
        if (propertyId == null) {
            throw new ApiException("Missing the required parameter 'propertyId' when calling propertiesPropertyIdGet(Async)");
        }
        

        okhttp3.Call localVarCall = propertiesPropertyIdGetCall(propertyId, _callback);
        return localVarCall;

    }

    /**
     * Get a properties details
     * Get all information about a specific property by its ID.
     * @param propertyId  (required)
     * @return InlineResponse2003
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, property found, the whole property object is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse2003 propertiesPropertyIdGet(String propertyId) throws ApiException {
        ApiResponse<InlineResponse2003> localVarResp = propertiesPropertyIdGetWithHttpInfo(propertyId);
        return localVarResp.getData();
    }

    /**
     * Get a properties details
     * Get all information about a specific property by its ID.
     * @param propertyId  (required)
     * @return ApiResponse&lt;InlineResponse2003&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, property found, the whole property object is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse2003> propertiesPropertyIdGetWithHttpInfo(String propertyId) throws ApiException {
        okhttp3.Call localVarCall = propertiesPropertyIdGetValidateBeforeCall(propertyId, null);
        Type localVarReturnType = new TypeToken<InlineResponse2003>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a properties details (asynchronously)
     * Get all information about a specific property by its ID.
     * @param propertyId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful, property found, the whole property object is returned. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> We validate all calls to our API in a strict manner using Zod. In case of any validation errors, we send back a 400 response with a list of all validation errors. For more info see https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Unauthorized, the api key in the \&quot;apiKey\&quot; header field is invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call propertiesPropertyIdGetAsync(String propertyId, final ApiCallback<InlineResponse2003> _callback) throws ApiException {

        okhttp3.Call localVarCall = propertiesPropertyIdGetValidateBeforeCall(propertyId, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse2003>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
