/*
 * lodgea-java
 * LODGEA SDK for Java. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lodgea.controllers;

import com.lodgea.ApiException;
import com.lodgea.model.PropertyGet;
import com.lodgea.model.V1PropertyGetPost200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PropertyApi
 */
@Disabled
public class PropertyApiTest {

    private final PropertyApi api = new PropertyApi();

    /**
     * Get Property by ID
     *
     * Get all information about a specific property by its ID. This parameter is required.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1PropertyGetPostTest() throws ApiException {
        PropertyGet propertyGet = null;
        V1PropertyGetPost200Response response = api.v1PropertyGetPost(propertyGet);
        // TODO: test validations
    }

}
